// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddressBookServiceClient is the client API for AddressBookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressBookServiceClient interface {
	GetAddressBook(ctx context.Context, in *GetAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error)
	CreateAddressBook(ctx context.Context, in *CreateAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error)
	UpdateAddressBook(ctx context.Context, in *UpdateAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error)
	DeleteAddressBook(ctx context.Context, in *DeleteAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error)
}

type addressBookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressBookServiceClient(cc grpc.ClientConnInterface) AddressBookServiceClient {
	return &addressBookServiceClient{cc}
}

func (c *addressBookServiceClient) GetAddressBook(ctx context.Context, in *GetAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error) {
	out := new(AddressBookResponse)
	err := c.cc.Invoke(ctx, "/address_book.v1.AddressBookService/GetAddressBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) CreateAddressBook(ctx context.Context, in *CreateAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error) {
	out := new(AddressBookResponse)
	err := c.cc.Invoke(ctx, "/address_book.v1.AddressBookService/CreateAddressBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) UpdateAddressBook(ctx context.Context, in *UpdateAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error) {
	out := new(AddressBookResponse)
	err := c.cc.Invoke(ctx, "/address_book.v1.AddressBookService/UpdateAddressBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) DeleteAddressBook(ctx context.Context, in *DeleteAddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error) {
	out := new(AddressBookResponse)
	err := c.cc.Invoke(ctx, "/address_book.v1.AddressBookService/DeleteAddressBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressBookServiceServer is the server API for AddressBookService service.
// All implementations must embed UnimplementedAddressBookServiceServer
// for forward compatibility
type AddressBookServiceServer interface {
	GetAddressBook(context.Context, *GetAddressBookRequest) (*AddressBookResponse, error)
	CreateAddressBook(context.Context, *CreateAddressBookRequest) (*AddressBookResponse, error)
	UpdateAddressBook(context.Context, *UpdateAddressBookRequest) (*AddressBookResponse, error)
	DeleteAddressBook(context.Context, *DeleteAddressBookRequest) (*AddressBookResponse, error)
	mustEmbedUnimplementedAddressBookServiceServer()
}

// UnimplementedAddressBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAddressBookServiceServer struct {
}

func (UnimplementedAddressBookServiceServer) GetAddressBook(context.Context, *GetAddressBookRequest) (*AddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressBook not implemented")
}
func (UnimplementedAddressBookServiceServer) CreateAddressBook(context.Context, *CreateAddressBookRequest) (*AddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddressBook not implemented")
}
func (UnimplementedAddressBookServiceServer) UpdateAddressBook(context.Context, *UpdateAddressBookRequest) (*AddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAddressBook not implemented")
}
func (UnimplementedAddressBookServiceServer) DeleteAddressBook(context.Context, *DeleteAddressBookRequest) (*AddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAddressBook not implemented")
}
func (UnimplementedAddressBookServiceServer) mustEmbedUnimplementedAddressBookServiceServer() {}

// UnsafeAddressBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressBookServiceServer will
// result in compilation errors.
type UnsafeAddressBookServiceServer interface {
	mustEmbedUnimplementedAddressBookServiceServer()
}

func RegisterAddressBookServiceServer(s grpc.ServiceRegistrar, srv AddressBookServiceServer) {
	s.RegisterService(&AddressBookService_ServiceDesc, srv)
}

func _AddressBookService_GetAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).GetAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_book.v1.AddressBookService/GetAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).GetAddressBook(ctx, req.(*GetAddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_CreateAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).CreateAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_book.v1.AddressBookService/CreateAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).CreateAddressBook(ctx, req.(*CreateAddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_UpdateAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).UpdateAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_book.v1.AddressBookService/UpdateAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).UpdateAddressBook(ctx, req.(*UpdateAddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_DeleteAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).DeleteAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_book.v1.AddressBookService/DeleteAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).DeleteAddressBook(ctx, req.(*DeleteAddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressBookService_ServiceDesc is the grpc.ServiceDesc for AddressBookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressBookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "address_book.v1.AddressBookService",
	HandlerType: (*AddressBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddressBook",
			Handler:    _AddressBookService_GetAddressBook_Handler,
		},
		{
			MethodName: "CreateAddressBook",
			Handler:    _AddressBookService_CreateAddressBook_Handler,
		},
		{
			MethodName: "UpdateAddressBook",
			Handler:    _AddressBookService_UpdateAddressBook_Handler,
		},
		{
			MethodName: "DeleteAddressBook",
			Handler:    _AddressBookService_DeleteAddressBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/address_book/v1/address_book.proto",
}
