// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/address_book/v1/address_book.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonBaseData_PhoneType int32

const (
	PersonBaseData_MOBILE    PersonBaseData_PhoneType = 0
	PersonBaseData_TELEPHONE PersonBaseData_PhoneType = 1
	PersonBaseData_HOME      PersonBaseData_PhoneType = 2
)

// Enum value maps for PersonBaseData_PhoneType.
var (
	PersonBaseData_PhoneType_name = map[int32]string{
		0: "MOBILE",
		1: "TELEPHONE",
		2: "HOME",
	}
	PersonBaseData_PhoneType_value = map[string]int32{
		"MOBILE":    0,
		"TELEPHONE": 1,
		"HOME":      2,
	}
)

func (x PersonBaseData_PhoneType) Enum() *PersonBaseData_PhoneType {
	p := new(PersonBaseData_PhoneType)
	*p = x
	return p
}

func (x PersonBaseData_PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonBaseData_PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_address_book_v1_address_book_proto_enumTypes[0].Descriptor()
}

func (PersonBaseData_PhoneType) Type() protoreflect.EnumType {
	return &file_api_address_book_v1_address_book_proto_enumTypes[0]
}

func (x PersonBaseData_PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonBaseData_PhoneType.Descriptor instead.
func (PersonBaseData_PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{0, 0}
}

type PersonBaseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email     string                   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneType PersonBaseData_PhoneType `protobuf:"varint,3,opt,name=phone_type,json=phoneType,proto3,enum=address_book.v1.PersonBaseData_PhoneType" json:"phone_type,omitempty"`
	Phone     string                   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *PersonBaseData) Reset() {
	*x = PersonBaseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonBaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonBaseData) ProtoMessage() {}

func (x *PersonBaseData) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonBaseData.ProtoReflect.Descriptor instead.
func (*PersonBaseData) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{0}
}

func (x *PersonBaseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonBaseData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PersonBaseData) GetPhoneType() PersonBaseData_PhoneType {
	if x != nil {
		return x.PhoneType
	}
	return PersonBaseData_MOBILE
}

func (x *PersonBaseData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseData *PersonBaseData `protobuf:"bytes,1,opt,name=baseData,proto3" json:"baseData,omitempty"`
	Id       int64           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetBaseData() *PersonBaseData {
	if x != nil {
		return x.BaseData
	}
	return nil
}

func (x *Person) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddressBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Preson []*Person `protobuf:"bytes,1,rep,name=preson,proto3" json:"preson,omitempty"`
}

func (x *AddressBook) Reset() {
	*x = AddressBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBook) ProtoMessage() {}

func (x *AddressBook) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBook.ProtoReflect.Descriptor instead.
func (*AddressBook) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{2}
}

func (x *AddressBook) GetPreson() []*Person {
	if x != nil {
		return x.Preson
	}
	return nil
}

type GetAddressBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAddressBookRequest) Reset() {
	*x = GetAddressBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddressBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressBookRequest) ProtoMessage() {}

func (x *GetAddressBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressBookRequest.ProtoReflect.Descriptor instead.
func (*GetAddressBookRequest) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddressBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateAddressBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonRequest *PersonBaseData `protobuf:"bytes,1,opt,name=person_request,json=personRequest,proto3" json:"person_request,omitempty"`
}

func (x *CreateAddressBookRequest) Reset() {
	*x = CreateAddressBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAddressBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressBookRequest) ProtoMessage() {}

func (x *CreateAddressBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressBookRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressBookRequest) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAddressBookRequest) GetPersonRequest() *PersonBaseData {
	if x != nil {
		return x.PersonRequest
	}
	return nil
}

type UpdateAddressBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonRequest *PersonBaseData `protobuf:"bytes,2,opt,name=person_request,json=personRequest,proto3" json:"person_request,omitempty"`
}

func (x *UpdateAddressBookRequest) Reset() {
	*x = UpdateAddressBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAddressBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressBookRequest) ProtoMessage() {}

func (x *UpdateAddressBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressBookRequest) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAddressBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressBookRequest) GetPersonRequest() *PersonBaseData {
	if x != nil {
		return x.PersonRequest
	}
	return nil
}

type DeleteAddressBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAddressBookRequest) Reset() {
	*x = DeleteAddressBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAddressBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressBookRequest) ProtoMessage() {}

func (x *DeleteAddressBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressBookRequest) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAddressBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddressBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonData *PersonBaseData `protobuf:"bytes,2,opt,name=person_data,json=personData,proto3" json:"person_data,omitempty"`
}

func (x *AddressBookResponse) Reset() {
	*x = AddressBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_address_book_v1_address_book_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBookResponse) ProtoMessage() {}

func (x *AddressBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_address_book_v1_address_book_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBookResponse.ProtoReflect.Descriptor instead.
func (*AddressBookResponse) Descriptor() ([]byte, []int) {
	return file_api_address_book_v1_address_book_proto_rawDescGZIP(), []int{7}
}

func (x *AddressBookResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressBookResponse) GetPersonData() *PersonBaseData {
	if x != nil {
		return x.PersonData
	}
	return nil
}

var File_api_address_book_v1_address_book_proto protoreflect.FileDescriptor

var file_api_address_book_v1_address_book_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f,
	0x6f, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x22, 0xcc, 0x01, 0x0a, 0x0e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x48, 0x0a, 0x0a, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x30, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x45, 0x4c, 0x45, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x48, 0x4f, 0x4d, 0x45, 0x10, 0x02, 0x22, 0x55, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62,
	0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42, 0x61, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x3e, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x2f,
	0x0a, 0x06, 0x70, 0x72, 0x65, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x72, 0x65, 0x73, 0x6f, 0x6e, 0x22,
	0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x62, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x18,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x67, 0x0a, 0x13,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x40, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x32, 0xa6, 0x03, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x26,
	0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f,
	0x6b, 0x12, 0x29, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x29, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x29, 0x2e,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20,
	0x5a, 0x1e, 0x77, 0x65, 0x65, 0x6b, 0x2d, 0x30, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_address_book_v1_address_book_proto_rawDescOnce sync.Once
	file_api_address_book_v1_address_book_proto_rawDescData = file_api_address_book_v1_address_book_proto_rawDesc
)

func file_api_address_book_v1_address_book_proto_rawDescGZIP() []byte {
	file_api_address_book_v1_address_book_proto_rawDescOnce.Do(func() {
		file_api_address_book_v1_address_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_address_book_v1_address_book_proto_rawDescData)
	})
	return file_api_address_book_v1_address_book_proto_rawDescData
}

var file_api_address_book_v1_address_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_address_book_v1_address_book_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_address_book_v1_address_book_proto_goTypes = []interface{}{
	(PersonBaseData_PhoneType)(0),    // 0: address_book.v1.PersonBaseData.PhoneType
	(*PersonBaseData)(nil),           // 1: address_book.v1.PersonBaseData
	(*Person)(nil),                   // 2: address_book.v1.Person
	(*AddressBook)(nil),              // 3: address_book.v1.AddressBook
	(*GetAddressBookRequest)(nil),    // 4: address_book.v1.GetAddressBookRequest
	(*CreateAddressBookRequest)(nil), // 5: address_book.v1.CreateAddressBookRequest
	(*UpdateAddressBookRequest)(nil), // 6: address_book.v1.UpdateAddressBookRequest
	(*DeleteAddressBookRequest)(nil), // 7: address_book.v1.DeleteAddressBookRequest
	(*AddressBookResponse)(nil),      // 8: address_book.v1.AddressBookResponse
}
var file_api_address_book_v1_address_book_proto_depIdxs = []int32{
	0,  // 0: address_book.v1.PersonBaseData.phone_type:type_name -> address_book.v1.PersonBaseData.PhoneType
	1,  // 1: address_book.v1.Person.baseData:type_name -> address_book.v1.PersonBaseData
	2,  // 2: address_book.v1.AddressBook.preson:type_name -> address_book.v1.Person
	1,  // 3: address_book.v1.CreateAddressBookRequest.person_request:type_name -> address_book.v1.PersonBaseData
	1,  // 4: address_book.v1.UpdateAddressBookRequest.person_request:type_name -> address_book.v1.PersonBaseData
	1,  // 5: address_book.v1.AddressBookResponse.person_data:type_name -> address_book.v1.PersonBaseData
	4,  // 6: address_book.v1.AddressBookService.GetAddressBook:input_type -> address_book.v1.GetAddressBookRequest
	5,  // 7: address_book.v1.AddressBookService.CreateAddressBook:input_type -> address_book.v1.CreateAddressBookRequest
	6,  // 8: address_book.v1.AddressBookService.UpdateAddressBook:input_type -> address_book.v1.UpdateAddressBookRequest
	7,  // 9: address_book.v1.AddressBookService.DeleteAddressBook:input_type -> address_book.v1.DeleteAddressBookRequest
	8,  // 10: address_book.v1.AddressBookService.GetAddressBook:output_type -> address_book.v1.AddressBookResponse
	8,  // 11: address_book.v1.AddressBookService.CreateAddressBook:output_type -> address_book.v1.AddressBookResponse
	8,  // 12: address_book.v1.AddressBookService.UpdateAddressBook:output_type -> address_book.v1.AddressBookResponse
	8,  // 13: address_book.v1.AddressBookService.DeleteAddressBook:output_type -> address_book.v1.AddressBookResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_address_book_v1_address_book_proto_init() }
func file_api_address_book_v1_address_book_proto_init() {
	if File_api_address_book_v1_address_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_address_book_v1_address_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonBaseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_book_v1_address_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_book_v1_address_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_book_v1_address_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddressBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_book_v1_address_book_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAddressBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_book_v1_address_book_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAddressBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_book_v1_address_book_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAddressBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_address_book_v1_address_book_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_address_book_v1_address_book_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_address_book_v1_address_book_proto_goTypes,
		DependencyIndexes: file_api_address_book_v1_address_book_proto_depIdxs,
		EnumInfos:         file_api_address_book_v1_address_book_proto_enumTypes,
		MessageInfos:      file_api_address_book_v1_address_book_proto_msgTypes,
	}.Build()
	File_api_address_book_v1_address_book_proto = out.File
	file_api_address_book_v1_address_book_proto_rawDesc = nil
	file_api_address_book_v1_address_book_proto_goTypes = nil
	file_api_address_book_v1_address_book_proto_depIdxs = nil
}
